# Generated by Django 3.2.3 on 2021-05-18 09:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_id', models.IntegerField(default=0)),
                ('no_of_rooms', models.IntegerField(default=0)),
                ('warden_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=100)),
                ('floors', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('month_bill', models.IntegerField(default=0)),
                ('month_name', models.CharField(default='0', max_length=20)),
                ('month_deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('no_of_students_occupied', models.IntegerField(default=0)),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.floor')),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.hostel')),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='supervisor_mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floor',
            name='hostel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.hostel'),
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_month', models.CharField(max_length=20)),
                ('fine_amount', models.IntegerField()),
                ('fine_deadline', models.DateField()),
                ('date_created', models.DateField(auto_now=True)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.hostel')),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('student_mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Accounts.authentication')),
                ('verified_by_supervisor', models.BooleanField(default=False)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(max_length=1)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('parent_mobile_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('yos', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1024)),
                ('assigned_room', models.IntegerField(default=-1)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='bill_payments',
            fields=[
                ('student_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Accounts.authentication')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_accepted', models.BooleanField(default=False)),
                ('payment_paid', models.BooleanField(default=False)),
                ('payment_rejected', models.BooleanField(default=False)),
                ('transaction_image', models.ImageField(blank=True, null=True, upload_to='Transactions/')),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.hostel')),
            ],
        ),
    ]
